services:
  database:
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - database
    logging:
      options:
        max-size: 10m

volumes:
  db-data: {}

networks:
  default:
    driver: bridge

